//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WerklijstHulpje.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>U1</string>
  <string>E3</string>
  <string>C8:I38</string>
  <string>J8:M38</string>
  <string>N8:R38</string>
  <string>T8:T37</string>
  <string>V41</string>
  <string>V44</string>
  <string>E40</string>
  <string>E49</string>
  <string>E50</string>
  <string>E51</string>
  <string>E52</string>
  <string>G53</string>
  <string>G54</string>
  <string>D42</string>
  <string>D43</string>
  <string>D44</string>
  <string>D45</string>
  <string>D46</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Ranges {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Ranges"]));
            }
            set {
                this["Ranges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>januari</string>
  <string>februari</string>
  <string>maart</string>
  <string>april</string>
  <string>mei</string>
  <string>juni</string>
  <string>juli</string>
  <string>augustus</string>
  <string>september</string>
  <string>oktober</string>
  <string>november</string>
  <string>december</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SheetMonths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SheetMonths"]));
            }
            set {
                this["SheetMonths"] = value;
            }
        }
    }
}
